### ISSUE TITLE
Sponsoring jOlm

### ISSUE THREAD

**Issue by brevilo** [brevilo/jolm#17]
Hey @brevilo, [...] respecting your work of jolm, we’d like to sponsor somehow. Please kindly let’s know how.

_Originally posted by @oncecrossover in https://github.com/brevilo/jolm/issues/16#issuecomment-993311703_

**Comment by brevilo** [comment]
Thanks for the offer. I appreciate that!

Please note that jOlm is a project I run in my spare time and that's not going to change. Furthermore, I'm not contributing to the Matrix ecosystem out of potential financial gain. I'm doing it solely out of idealism. Thus money isn't an incentive for me personally. Also, getting paid would probably set false expectations like a certain maximum response time or entitlements to new features. Sorry, money can't buy you that.

That said, there are ways to "sponsor" jOlm in ways that would benefit everyone. As I mentioned in the [status report](https://github.com/brevilo/jolm#status) I'd like to see security and memory management audits at the some point. ~While I still have a few things I want to implement in that area for the upcoming v1.1 release (next week'ish),~ it would be really great to have an *external* review of jOlm with regards to potential security issues and/or architectural flaws - by *real* experts in the field. These could either be interested security researchers or a renowned company offering such a service.

Taking upstream [`libolm`](https://gitlab.matrix.org/matrix-org/olm#security-assessment) as a fitting example, they got reviewed by [NCC Group](https://www.nccgroup.com). No idea what such a review would cost but since jOlm just provides bindings to `libolm` a security review should be easier and quicker, and thus cheaper.

Another type of "sponsoring" could mean becoming part of the jOlm team, i.e. sponsor time of a professional developer to the project to deal with issues, new features and PRs. Having said that, though, this kind of sponsoring should be pretty ineffective in case of jOlm. The reason being that there won't be that much work to do as soon as it matured enough. jOlm won't have a constant stream of new features like other products. It just needs to be kept up to date with upstream and get a few improvements here and there. Therefore, I don't really see the need for this right now.

Effectively, this only leaves the option to sponsor said external security review in some way or form.

Is that something you could consider?

Cheers

**Comment by oncecrossover** [comment]
Hey @brevilo , I apologize for my lateness. 
We are willing to sponsor some audit fees, please leave contact information.

**Comment by brevilo** [comment]
No worries 👍

There's no need to involve myself. To the contrary, it is way easier for everyone the fewer parties are involved. I suggest you just hire any audit company you see fit. I provided one example above. Should there be any changes required I'll be more than happy to accept PRs from said company (or you). jOlm is open source software after all, so you've got everything you need to go ahead.

Thanks!

**Comment by brevilo** [comment]
Development of jOlm is coming to an end, at least for the time being. Details can be found in the latest [status](https://github.com/brevilo/jolm#status) update.

Cheers
